/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "U_ADC.h"
#include "U_ADC_aliases.h"
#include "GLCD_SPIM.h"
#include "GLCD_SPIM_SPI_UART.h"
#include "GLCD_SPIM_PINS.h"
#include "GLCD_SPIM_SPI_UART_PVT.h"
#include "GLCD_SPIM_PVT.h"
#include "GLCD_SPIM_BOOT.h"
#include "Timer_1.h"
#include "isr_1.h"
#include "Clock_1.h"
#include "N_ADC.h"
#include "N_ADC_aliases.h"
#include "GLCD_PSB.h"
#include "GLCD_PSB_aliases.h"
#include "GLCD_CS.h"
#include "GLCD_CS_aliases.h"
#include "GLCD_RST.h"
#include "GLCD_RST_aliases.h"
#include "V_ADC.h"
#include "V_ADC_aliases.h"
#include "W_ADC.h"
#include "W_ADC_aliases.h"
#include "MUX_A.h"
#include "MUX_A_aliases.h"
#include "MUX_B.h"
#include "MUX_B_aliases.h"
#include "MUX_C.h"
#include "MUX_C_aliases.h"
#include "X1_ADC.h"
#include "X1_ADC_aliases.h"
#include "L3_ADC.h"
#include "L3_ADC_aliases.h"
#include "NL_ADC.h"
#include "NL_ADC_aliases.h"
#include "I3_ADC.h"
#include "I3_ADC_aliases.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "GLCD_SPIM_SCBCLK.h"
#include "GLCD_SPIM_sclk_m.h"
#include "GLCD_SPIM_sclk_m_aliases.h"
#include "GLCD_SPIM_mosi_m.h"
#include "GLCD_SPIM_mosi_m_aliases.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

