/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "RTC.h"
#include "LCD.h"
#include "Pin_Ctrl.h"
#include "Pin_Ctrl_aliases.h"
#include "Pin_7Seg.h"
#include "Pin_7Seg_aliases.h"
#include "Timer_1.h"
#include "isr_1.h"
#include "Clock_1.h"
#include "ADC.h"
#include "LM35.h"
#include "LM35_aliases.h"
#include "UART.h"
#include "isr_rx.h"
#include "PWM_1.h"
#include "Clock_2.h"
#include "Pin_pwm1.h"
#include "Pin_pwm1_aliases.h"
#include "PWM_2.h"
#include "Clock_3.h"
#include "Pin_pwm2.h"
#include "Pin_pwm2_aliases.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "UART_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

